In [1]:
import numpy as np
import pandas as pd

In [24]:
df = pd.DataFrame({'col1' : [1,2,3,4],'col2' : [444,555,666,444],'col3' : ['abc','def','ghi','xyz']})

In [25]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [26]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [27]:
df['col2'].nunique()

3

In [28]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [29]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [30]:
newdf

col1  col2 col3
3     4   444  xyz

In [31]:
#Applying Functions
def times2(x):
    return x*2

In [32]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [21]:
df['col1'].sum()

10

In [33]:
del df['col1']

In [34]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [35]:
df.columnsdf.index

Index(['col2', 'col3'], dtype='object')

In [36]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [39]:
df.sort_values(by='col2') #inplace=False by default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [41]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [43]:
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [44]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [45]:
df.fillna('FILL')

col1  col2 col3
0     1  FILL  abc
1     2   555  def
2     3   666  ghi
3  FILL   444  xyz

In [46]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [47]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [49]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [50]:
#Creating sample array
arr = np.arange(0,11)

In [51]:
arr[1:5]

array([1, 2, 3, 4])

In [52]:
#Broadcasting
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

#Show
arr#Important notes on Slices


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr#To get a copy, need to be explicit


array([0, 1, 2, 3, 4, 5])

In [56]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [60]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [61]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [62]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [63]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [64]:
#Set up matrix
arr2d = np.zeros((10,10))

In [66]:
#Length of array
arr_length = arr2d.shape[1]

In [67]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [68]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [69]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [70]:
#Selection
arr = np.arange(1,11)
arr
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [71]:
bool_arr = arr>4

In [72]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [74]:
np.array(my_list)

array([1, 2, 3])

In [75]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [76]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [79]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [80]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [81]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [82]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [85]:
#uniform distribution over [0, 1)
np.random.rand(5,5)

array([[ 0.79059913,  0.89500749,  0.57859214,  0.1371482 ,  0.00372449],
       [ 0.5093496 ,  0.0860064 ,  0.80980371,  0.96777385,  0.37546153],
       [ 0.25812643,  0.15818753,  0.41306954,  0.74657601,  0.45737498],
       [ 0.66208575,  0.2649597 ,  0.61067579,  0.98002061,  0.91621488],
       [ 0.24086212,  0.01778445,  0.18451795,  0.38333379,  0.40737244]])

In [84]:
#"standard normal" distribution
np.random.randn(5,5)

array([[ 0.68972193, -2.47367372,  0.58462518,  0.29114787,  0.68406602],
       [ 0.39621024, -0.80640364, -0.37738668, -0.81204078,  1.94213578],
       [-0.60783111, -0.22237735,  1.50709511,  0.09101186,  0.19096653],
       [-0.39141966,  0.0485759 , -1.68624293, -1.79083976,  0.29498497],
       [ 1.89000469,  0.10101625, -0.65719239,  0.98770052,  1.94937684]])

In [86]:
np.random.randint(1,100)

3

In [87]:
np.random.randint(1,100,10)

array([22, 78, 57, 85, 57, 13, 89, 32, 36, 18])

In [88]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [89]:
ranarr

array([45,  0, 24, 27, 16, 47,  2, 43, 37,  0])

In [90]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
ranarr

array([45,  0, 24, 27, 16, 47,  2, 43, 37,  0])

In [92]:
ranarr.max()

47

In [93]:
ranarr.argmax()

5

In [94]:
ranarr.min()

0

In [95]:
ranarr.argmin()

1

In [96]:
arr.shape

(25,)

In [103]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [104]:
arr.dtype

dtype('int32')

In [105]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [106]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [107]:
mat[3,4]

20

In [108]:
mat[0:,1:][:3,:1]

array([[ 2],
       [ 7],
       [12]])

In [109]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [110]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
mat.sum()

325

In [112]:
mat.std()

7.2111025509279782

In [113]:
mat.sum(0)

array([55, 60, 65, 70, 75])